#!/usr/bin/env python3
"""
rdcore_check.py — verify every copy of the engine agrees.

Why this is a CHECK and not a build
-----------------------------------
RDCore must exist in exactly ONE place or the tools silently disagree about what
"on-track" means. That place is rdcore.js, and build.py is the ONLY thing that
writes it into an app:

    rdcore.js + *_app.template.html  --build.py-->  *_app.html

An earlier version of this script ALSO wrote *_app.html, in place, from its own
copy of the engine. That made two writers with two sources for one file: whichever
ran last won, and because this one edits the BUILT artifact while build.py
regenerates it from the TEMPLATE, its edits were erased by the next build anyway.
So it does not write any more. It answers one question build.py cannot:

    do the DEPLOYED copies still match the repo's rdcore.js?

Three copies exist and can drift apart:
  1. rdcore.js                 the canonical engine (source of truth)
  2. *_app.html                inlined, so the apps keep working offline
  3. <broker>/rdcore.js        fetched at runtime by the R&D Hub, which cannot
                               render without broker data anyway

(2) drifts if someone hand-edits a built app or ships one without rebuilding.
(3) drifts whenever rdcore.js is committed but the broker is not redeployed —
and that is the dangerous one, because the Hub and the apps then band the same
score differently with nothing on screen to say so.

Usage
-----
  python rdcore_check.py                          # repo engine vs the inlined app copies
  python rdcore_check.py --broker https://host    # also compare the deployed broker copy
  exit 1 on any drift  (CI / pre-commit)

To FIX drift: edit rdcore.js, run `python build.py`, commit, redeploy the broker.
"""

import argparse
import hashlib
import os
import sys

MARK_START_PREFIX = "/* ==RDCORE_START=="
MARK_END = "/* ==RDCORE_END== */"

DEFAULT_APPS = ["planning_app.html", "execution_app.html", "product_designer.html"]
DEFAULT_CORE = "rdcore.js"


# ----------------------------------------------------------------- io helpers
def detect_eol(raw: bytes) -> str:
    """Dominant line ending of a file. Ties favour LF."""
    crlf = raw.count(b"\r\n")
    lf = raw.count(b"\n") - crlf
    return "\r\n" if crlf > lf else "\n"


def read_text(path: str):
    """Read a file, normalising to \\n for processing. Returns (text, eol)."""
    raw = open(path, "rb").read()
    eol = detect_eol(raw)
    return raw.decode("utf-8").replace("\r\n", "\n"), eol


def write_text(path: str, text: str, eol: str) -> None:
    """Write text back using the file's original line ending."""
    out = text.replace("\n", eol) if eol == "\r\n" else text
    open(path, "wb").write(out.encode("utf-8"))


def digest_of(core_text: str) -> str:
    """Content hash of the canonical engine, computed on the normalised text so
    it is identical regardless of the host file's line endings."""
    return hashlib.sha256(core_text.strip().encode("utf-8")).hexdigest()[:16]


# -------------------------------------------------------------- block finding
def find_block(text: str):
    """Locate the whole <script>...</script> housing RDCore. Returns (start, end)
    or None. Prefers the markers; falls back to the UMD tail for a first run."""
    i = text.find(MARK_START_PREFIX)
    if i < 0:
        i = text.find("root.RDCore = API;")  # unmarked: first run
        if i < 0:
            return None
    start = text.rfind("<script>", 0, i)
    end = text.find("</script>", i)
    if start < 0 or end < 0:
        return None
    return start, end + len("</script>")


def extract_core(text: str):
    """Pull the engine text back out of an app, for verification. Returns the
    engine source (normalised), or None if no RDCore block is present."""
    span = find_block(text)
    if not span:
        return None
    block = text[span[0]:span[1]]
    inner = block[len("<script>"):-len("</script>")]
    # Marked block: strip the marker lines. Unmarked: the inner IS the engine.
    j = inner.find(MARK_START_PREFIX)
    if j >= 0:
        nl = inner.find("\n", j)
        k = inner.rfind(MARK_END)
        inner = inner[nl + 1:k]
    return inner.strip()


def make_block(core_text: str, digest: str) -> str:
    return (
        "<script>{p} sha256:{d} — generated by build_rdcore.py; edit rdcore.js instead */\n"
        "{core}\n"
        "{end}</script>"
    ).format(p=MARK_START_PREFIX, d=digest, core=core_text.strip(), end=MARK_END)


# ---------------------------------------------------------------------- main
def process(app_path: str, core_text: str):
    """Compare an app's inlined engine against the canonical one. Never writes —
    build.py owns that. Returns (status, detail); status in {'ok','drift','missing','error'}."""
    if not os.path.exists(app_path):
        return "missing", "file not found"
    text, eol = read_text(app_path)
    if not find_block(text):
        return "error", "no RDCore block found (no markers, no `root.RDCore = API;`)"
    current = extract_core(text)
    if current == core_text.strip():
        return "ok", f"matches {DEFAULT_CORE} ({eol_name(eol)})"
    return "drift", f"inlined copy differs from {DEFAULT_CORE} — run `python build.py`"


def check_broker(base: str, digest: str):
    """Compare the DEPLOYED engine the Hub loads against the repo's. The broker's
    etag is sha256(text.strip())[:16] — the same digest_of() computes, so the two
    are directly comparable."""
    import json as _json
    import urllib.request
    # A bare host ("host.railway.app") is the natural thing to paste, and urllib rejects it with the
    # unhelpful "unknown url type". Default the scheme instead of lecturing.
    base = base.strip().rstrip("/")
    if "://" not in base:
        base = "https://" + base
    url = base + "/rdcore/version"
    try:
        with urllib.request.urlopen(url, timeout=10) as r:
            etag = (_json.loads(r.read()) or {}).get("etag")
    except Exception as e:
        return "error", f"{url}: {e}"
    if not etag:
        return "error", f"{url}: no etag in response"
    if etag == digest:
        return "ok", f"broker serves the same engine (sha256:{etag})"
    return "drift", (f"broker serves sha256:{etag}, repo has sha256:{digest} — "
                     f"the Hub and the apps are running DIFFERENT engines; redeploy the broker")


def eol_name(eol: str) -> str:
    return "CRLF" if eol == "\r\n" else "LF"


def main() -> int:
    ap = argparse.ArgumentParser(description="Verify every copy of RDCore matches rdcore.js. Never writes.")
    ap.add_argument("--core", default=DEFAULT_CORE, help="canonical engine (default: rdcore.js)")
    ap.add_argument("--apps", nargs="*", default=DEFAULT_APPS, help="app HTML files to check")
    ap.add_argument("--broker", default=os.environ.get("RD_BROKER", ""),
                    help="broker base URL; also compares the copy the Hub loads")
    ap.add_argument("--check", action="store_true", help="accepted and ignored; this tool only ever checks")
    args = ap.parse_args()

    if not os.path.exists(args.core):
        print(f"error: canonical engine not found: {args.core}", file=sys.stderr)
        return 2
    core_text, _ = read_text(args.core)
    digest = digest_of(core_text)

    print(f"checking against {args.core}  sha256:{digest}\n")
    worst = 0
    checked = 0
    drifted = 0
    for app in args.apps:
        status, detail = process(app, core_text)
        symbol = {"ok": "  ok  ", "drift": " DRIFT", "missing": " skip ", "error": " ERROR"}[status]
        print(f"[{symbol}] {os.path.basename(app):26} {detail}")
        if status in ("drift", "error"):
            worst = 1
        if status == "drift":
            drifted = 1
        if status != "missing":
            checked += 1

    if args.broker:
        status, detail = check_broker(args.broker, digest)
        symbol = {"ok": "  ok  ", "drift": " DRIFT", "error": " ERROR"}[status]
        print(f"[{symbol}] {'broker (Hub loads this)':26} {detail}")
        if status in ("drift", "error"):
            worst = 1
        if status == "drift":
            drifted = 1
    else:
        print("\n  note: broker not checked (pass --broker <url> or set RD_BROKER).")
        print("        The Hub loads its engine from the broker, so a repo/broker mismatch")
        print("        is invisible until the two band the same score differently.")

    print()
    if not checked and not args.broker:
        # "all copies match" when zero copies were examined is the exact false green sweep.py exists to prevent
        print("ERROR: no app files found to check — nothing was verified.", file=sys.stderr)
        print(f"       looked for: {', '.join(DEFAULT_APPS)} in {os.getcwd()}", file=sys.stderr)
        return 2
    if drifted:
        print("drift detected — edit rdcore.js, run `python build.py`, then redeploy the broker")
    elif worst:
        print(f"all {checked} inlined copies match rdcore.js, but a check could not run (see ERROR above)")
    else:
        print(f"all {checked} inlined copies match rdcore.js")
    return worst


if __name__ == "__main__":
    sys.exit(main())
