#!/usr/bin/env python3
"""
build_rdcore.py — push the canonical RDCore into the app shells.

Why this exists
---------------
RDCore owns scoring, banding, and classification for every tool. It must exist
in exactly ONE place or the tools silently disagree about what "on-track" means.
That place is rdcore.js. This script is the only thing allowed to write the
copy that lives inside each app's HTML.

Why the apps inline it at all
-----------------------------
The apps have a working offline mode ("no broker token yet ... showing local
scratch"). Loading RDCore from the broker via <script src> would kill that mode
whenever the broker is unreachable, so the apps keep a self-contained copy and
this build keeps that copy honest.

The R&D Hub is the opposite case: it cannot render anything without broker data,
so a broker dependency for the engine costs it nothing. The Hub therefore loads
<broker>/rdcore.js at runtime and picks up changes — including band threshold
changes — with no redeploy. That is the whole point of the split.

The workflow
------------
  1. edit rdcore.js                     (the single source of truth)
  2. python build_rdcore.py             (inlines it into the apps)
  3. commit rdcore.js + the apps; deploy the broker
     -> apps carry the new copy; the Hub picks it up from the broker on reload

  python build_rdcore.py --check        (verify only; exit 1 on drift — CI/pre-commit)

Line endings
------------
planning_app.html and execution_app.html are CRLF; product_designer.html is LF.
Each file's dominant convention is detected and preserved, so this never
produces a whole-file diff.

The inlined block is delimited by hash-carrying markers, mirroring the
==CORE_START==/==CORE_END== convention already used in q-tracker-division.html.
The first run adopts an existing unmarked block by locating `root.RDCore = API;`;
later runs match on the markers.
"""

import argparse
import hashlib
import os
import sys

MARK_START_PREFIX = "/* ==RDCORE_START=="
MARK_END = "/* ==RDCORE_END== */"

DEFAULT_APPS = ["planning_app.html", "execution_app.html", "product_designer.html"]
DEFAULT_CORE = "rdcore.js"


# ----------------------------------------------------------------- io helpers
def detect_eol(raw: bytes) -> str:
    """Dominant line ending of a file. Ties favour LF."""
    crlf = raw.count(b"\r\n")
    lf = raw.count(b"\n") - crlf
    return "\r\n" if crlf > lf else "\n"


def read_text(path: str):
    """Read a file, normalising to \\n for processing. Returns (text, eol)."""
    raw = open(path, "rb").read()
    eol = detect_eol(raw)
    return raw.decode("utf-8").replace("\r\n", "\n"), eol


def write_text(path: str, text: str, eol: str) -> None:
    """Write text back using the file's original line ending."""
    out = text.replace("\n", eol) if eol == "\r\n" else text
    open(path, "wb").write(out.encode("utf-8"))


def digest_of(core_text: str) -> str:
    """Content hash of the canonical engine, computed on the normalised text so
    it is identical regardless of the host file's line endings."""
    return hashlib.sha256(core_text.strip().encode("utf-8")).hexdigest()[:16]


# -------------------------------------------------------------- block finding
def find_block(text: str):
    """Locate the whole <script>...</script> housing RDCore. Returns (start, end)
    or None. Prefers the markers; falls back to the UMD tail for a first run."""
    i = text.find(MARK_START_PREFIX)
    if i < 0:
        i = text.find("root.RDCore = API;")  # unmarked: first run
        if i < 0:
            return None
    start = text.rfind("<script>", 0, i)
    end = text.find("</script>", i)
    if start < 0 or end < 0:
        return None
    return start, end + len("</script>")


def extract_core(text: str):
    """Pull the engine text back out of an app, for verification. Returns the
    engine source (normalised), or None if no RDCore block is present."""
    span = find_block(text)
    if not span:
        return None
    block = text[span[0]:span[1]]
    inner = block[len("<script>"):-len("</script>")]
    # Marked block: strip the marker lines. Unmarked: the inner IS the engine.
    j = inner.find(MARK_START_PREFIX)
    if j >= 0:
        nl = inner.find("\n", j)
        k = inner.rfind(MARK_END)
        inner = inner[nl + 1:k]
    return inner.strip()


def make_block(core_text: str, digest: str) -> str:
    return (
        "<script>{p} sha256:{d} — generated by build_rdcore.py; edit rdcore.js instead */\n"
        "{core}\n"
        "{end}</script>"
    ).format(p=MARK_START_PREFIX, d=digest, core=core_text.strip(), end=MARK_END)


# ---------------------------------------------------------------------- main
def process(app_path: str, core_text: str, digest: str, check_only: bool):
    """Returns (status, detail). status in {'ok','updated','drift','missing','error'}."""
    if not os.path.exists(app_path):
        return "missing", "file not found"
    text, eol = read_text(app_path)
    span = find_block(text)
    if not span:
        return "error", "no RDCore block found (no markers, no `root.RDCore = API;`)"

    current = extract_core(text)
    if current == core_text.strip():
        return "ok", f"already current ({eol_name(eol)})"
    if check_only:
        return "drift", f"inlined copy differs from {DEFAULT_CORE}"

    new_text = text[:span[0]] + make_block(core_text, digest) + text[span[1]:]
    write_text(app_path, new_text, eol)

    # Verify the round-trip: re-read and re-extract must equal the canonical.
    back, _ = read_text(app_path)
    if extract_core(back) != core_text.strip():
        return "error", "post-write verification FAILED — file may be corrupt"
    return "updated", f"inlined {len(core_text)} chars ({eol_name(eol)} preserved)"


def eol_name(eol: str) -> str:
    return "CRLF" if eol == "\r\n" else "LF"


def main() -> int:
    ap = argparse.ArgumentParser(description="Inline the canonical RDCore into the app shells.")
    ap.add_argument("--core", default=DEFAULT_CORE, help="canonical engine (default: rdcore.js)")
    ap.add_argument("--apps", nargs="*", default=DEFAULT_APPS, help="app HTML files to update")
    ap.add_argument("--check", action="store_true", help="verify only; exit 1 on drift")
    args = ap.parse_args()

    if not os.path.exists(args.core):
        print(f"error: canonical engine not found: {args.core}", file=sys.stderr)
        return 2
    core_text, _ = read_text(args.core)
    digest = digest_of(core_text)

    print(f"{'checking' if args.check else 'building'} against {args.core}  sha256:{digest}\n")
    worst = 0
    for app in args.apps:
        status, detail = process(app, core_text, digest, args.check)
        symbol = {"ok": "  ok  ", "updated": " wrote", "drift": " DRIFT",
                  "missing": " skip ", "error": " ERROR"}[status]
        print(f"[{symbol}] {os.path.basename(app):26} {detail}")
        if status in ("drift", "error"):
            worst = 1
        elif status == "missing" and worst == 0:
            worst = 0  # a missing app is a warning, not a failure

    print()
    if args.check:
        print("drift detected — run without --check to fix" if worst else "all inlined copies match rdcore.js")
    else:
        print("done — commit rdcore.js and the apps, then deploy the broker so the Hub picks it up")
    return worst


if __name__ == "__main__":
    sys.exit(main())
